# -*- coding: utf-8 -*-
"""Data-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWdWiEKCX6mmMGCyMjlQuI1we2ZYp81K

# **IMPORTING LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **LOAD DATA**"""

df = pd.read_csv('/content/SALES(2025-01--2025-12)Detailed.csv')
df.head()

"""# **BASIC UNDERSTANDING OF DATA**"""

df.shape

df.info()

df.describe()

"""# **CONVERSION OF DATA TYPE**"""

df['Date'] = pd.to_datetime(df['Date'])

df.rename(columns={'InvoiceDate': 'Date'}, inplace=True)
df['Date'] = pd.to_datetime(df['Date'])

monthly_sales = df.groupby(df['Date'].dt.month)['Sales'].sum()

"""# **VISUALIZATION**

# **MONTHLY SALES TREND**
"""

monthly_sales = df.groupby(df['Date'].dt.month)['ValueNp'].sum()

plt.figure(figsize=(8,5))
monthly_sales.plot()
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales Value')
plt.grid()
plt.show()

"""# **SALES BY TEAM**"""

team_sales = df.groupby('TeamName')['ValueNp'].sum().sort_values(ascending=False)

plt.figure(figsize=(10,5))
team_sales.plot(kind='bar')
plt.title('Sales by Team')
plt.xlabel('Team Name')
plt.ylabel('Sales Value')
plt.show()

"""# **TOP 10 PRODUCTS BY SALES VALUE**"""

top_products = (
    df.groupby('ProductName')['ValueNp']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10,5))
top_products.plot(kind='bar')
plt.title('Top 10 Products by Sales Value')
plt.xlabel('Product Name')
plt.ylabel('Sales Value')
plt.show()

"""# **UNITS SOLD BY PRODUCT (VOLUME ANALYSIS)**"""

top_units = (
    df.groupby('ProductName')['Units']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10,5))
top_units.plot(kind='bar')
plt.title('Top 10 Products by Units Sold')
plt.xlabel('Product Name')
plt.ylabel('Units Sold')
plt.show()

"""# **DISCOUNT VS SALES VALUE**"""

plt.figure(figsize=(8,5))
plt.scatter(df['Discount'], df['ValueNp'], alpha=0.5)
plt.title('Discount vs Sales Value')
plt.xlabel('Discount')
plt.ylabel('Sales Value')
plt.show()

"""# **CORRELATION HEATMAP (DATA SCIENCE BRIDGE)**"""

numeric_cols = ['Units', 'Bonus', 'Discount', 'TPrice', 'ValueNp']
corr = df[numeric_cols].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# **SALES BY DISTRIBUTOR (TOP 10)**"""

top_distributors = (
    df.groupby('DistributorName')['ValueNp']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10,5))
top_distributors.plot(kind='bar')
plt.title('Top 10 Distributors by Sales')
plt.xlabel('Distributor')
plt.ylabel('Sales Value')
plt.show()













