# -*- coding: utf-8 -*-
"""ML-MODELLING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lwhm-FWl10eoDXZx7xeTO1yPv-Sr-tXm

# **Import Libraries**
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.read_csv(
    '/content/SALES(2025-01--2025-12)Detailed.csv',
    engine='python',
    on_bad_lines='skip'
)

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

"""# **Handle Missing Values**"""

df['ClientType'].fillna('Unknown', inplace=True)
df['StockBatch'].fillna('Unknown', inplace=True)

numeric_cols = ['Units', 'Bonus', 'Discount', 'TPrice', 'ValueNp']
df[numeric_cols] = df[numeric_cols].fillna(0)

"""# **Feature Engineering**"""

df['TotalUnits'] = df['Units'] + df['Bonus']
df['Month'] = df['InvoiceDate'].dt.month

"""# **Feature Selection**"""

X = df[['TotalUnits', 'Discount', 'TPrice', 'Month']]
y = df['ValueNp']

"""# **Train–Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# **Train ML Model (Random Forest)**"""

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

"""# **Model Evaluation**"""

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

joblib.dump(model, 'ML-MODELLING.pkl')

!zip ML-MODELLING.zip ML-MODELLING.pkl







